# The logger options manager


#' Constants for 'futile.logger'
#' 
#' The logging configuration is managed by 'logger.options', a function
#' generated by OptionsManager within 'futile.options'. Other constants defined
#' include the log levels.
#' 
#' Constants provided by 'futile.logger'.
#' 
#' @aliases logger.options FATAL ERROR WARN INFO DEBUG TRACE
#' @author Brian Lee Yung Rowe
#' @seealso \code{futile.options}
#' @keywords data
logger.options <- OptionsManager('logger.options')

